#!/bin/bash

LOGFILE="/tmp/usb-lockdown.log"
RUID=$(who | awk 'FNR == 1 {print $1}')
RUSER_UID=$(id -u ${RUID})

# 장치 차단 및 차단 해제
case $1 in
    lockdown)
        # 장치의 유형별로 전체 차단
        if [ -f "/sys${DEVPATH%/*}/authorized" ]; then

            # 벤더 프로덕트 ID 확인
            if [ -f "/sys${DEVPATH%/*}/idVendor" ]; then
                VENDOR=$(cat /sys${DEVPATH%/*}/idVendor)
            fi
            if [ -f "/sys${DEVPATH%/*}/idProduct" ]; then
                PRODUCT=$(cat /sys${DEVPATH%/*}/idProduct)
            
            fi

            sudo -u ${RUID} DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/${RUSER_UID}/bus" zenity --error --width=300 --height=100 --text "허용된 USB 만 사용 가능합니다.\n\n관리자에 의해서 이 USB 장치 사용이 금지되었습니다.\n\n관리자에게 >문의하세요.\n\nVendor:Product = $VENDOR:$PRODUCT"

            echo 0 | tee /sys${DEVPATH%/*}/authorized | tee -a $LOGFILE
        fi
    ;;

    allow)
        # 특정 장치의 USB 허용
        if [ -f "/sys${DEVPATH%/*}/authorized" ]; then
            echo 1 | tee /sys${DEVPATH%/*}/authorized | tee -a $LOGFILE
        fi
    ;;
esac