{
 "title": "hamonize-monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "host",
    "query": "select pc_uuid from tbl_pc_mangr"
   }
  ]
 },
 "panels": [
  {
   "title": "Runtime",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uptime_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "uptime" }
     ]
    }
   ]
  },
  {
   "title": "Used Cpu",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu_value",
     "query": "SELECT mean(value) FROM \"cpu_value\" WHERE (\"host\" =~ /^$host$/ AND \"type\" = 'percent' AND \"type_instance\" = 'user') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "percent" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "user" }
     ]
    }
   ]
  },
  {
   "title": "Used Memory",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "percent" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "used" }
     ]
    }
   ]
  },
  {
   "title": "Used Swap Memory",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "swap_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "used" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "percent" }
     ]
    }
   ]
  },
  {
   "title": "Used Root Disk",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "df_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "root" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "percent_bytes" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "used" }
     ]
    }
   ]
  },
  {
   "title": "Cpu",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "user",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu_value",
     "query": "SELECT mean(\"value\") FROM \"cpu_value\" WHERE (\"type_instance\" = 'user' AND \"type\" = 'percent' AND \"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval), \"instance\" fill(null) ORDER BY time DESC",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "user" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "percent" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "wait",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu_value",
     "query": "SELECT mean(\"value\") FROM \"cpu_value\" WHERE (\"type_instance\" = 'user' AND \"type\" = 'percent' AND \"host\" =~ /^$host$/ ) AND $timeFilter GROUP BY time($__interval) fill(null) ORDER BY time DESC",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "wait" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "percent" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "system",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu_value",
     "query": "SELECT mean(\"value\") FROM \"cpu_value\" WHERE (\"type_instance\" = 'system' AND \"type\" = 'percent' AND \"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval) fill(null) ORDER BY time DESC",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "system" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "percent" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "idle",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu_value",
     "query": "SELECT mean(\"value\") FROM \"cpu_value\" WHERE (\"type_instance\" = 'idle' AND \"type\" = 'percent' AND \"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval) fill(null) ORDER BY time DESC",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "idle" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "percent" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "used",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory_value",
     "query": "SELECT mean(\"value\") FROM \"memory_value\" WHERE (\"host\" =~ /^$host$/ AND \"type_instance\" = 'used') AND $timeFilter GROUP BY time($__interval) fill(null) ORDER BY time DESC",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "used" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "memory" }
     ]
    },
    {
     "alias": "free",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "free" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "memory" }
     ]
    },
    {
     "alias": "cached",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "cached" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "memory" }
     ]
    },
    {
     "alias": "buffered",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "buffered" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "memory" }
     ]
    },
    {
     "alias": "slab_recl",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "slab_recl" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "memory" }
     ]
    },
    {
     "alias": "slab_unrecl",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "slab_unrecl" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "memory" }
     ]
    }
   ]
  },
  {
   "title": "Disk",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "Total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"value\") FROM \"df_value\" WHERE (\"host\" =~ /^$host$/ AND \"type\" = 'df_complex' AND \"instance\" = 'root' AND (\"type_instance\" = 'free' OR \"type_instance\" = 'used')) AND $timeFilter GROUP BY time(10s) fill(null) ORDER BY time ASC",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "free",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "df_value",
     "query": "SELECT sum(\"value\") FROM \"df_value\" WHERE (\"host\" =~ /^$host$/ AND \"type\" = 'df_complex' AND \"instance\" = 'root' AND \"type_instance\" = 'free') AND $timeFilter GROUP BY time($__interval) fill(null) ORDER BY time DESC",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "free" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "df_complex" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "root" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "free" }
     ]
    },
    {
     "alias": "used",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "df_value",
     "query": "SELECT sum(\"value\") FROM \"df_value\" WHERE (\"host\" =~ /^$host$/ AND \"type\" = 'percent_bytes' AND \"type_instance\" = 'used') AND $timeFilter GROUP BY time($__interval) fill(null) ORDER BY time DESC",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "used" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "df_complex" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "root" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "used" }
     ]
    }
   ]
  },
  {
   "title": "NetWork",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "interface_rx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "interface_tx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  }
 ]
}