#!/bin/bash

set -e

gtk-update-icon-cache


systemctl daemon-reload
systemctl enable hamonize-agent




systemctl enable hamonize-agentmngr

systemctl restart hamonize-agent
systemctl restart hamonize-agentmngr
