#!/bin/bash

set -e

gtk-update-icon-cache


# hamonize-agent service 
systemctl stop hamonize-agentmngr
systemctl disable hamonize-agentmngr

# hamonize-agent node 
systemctl stop hamonize-agent
systemctl disable hamonize-agent

# sudo rm -r /lib/systemd/system/hamonize-agent.service
# sudo rm -r /lib/systemd/system/hamonize-agentmngr

systemctl daemon-reload

# remove device contol
# cd /usr/share/hamonize-agent/usb-lockdown
# make clean

# delete hamonize-agent folder
rm -fr /usr/share/hamonize-agent
