#!/bin/bash

. /etc/hamonize/propertiesJob/propertiesInfo.hm

hw_path="/etc/hamonize/hwchk"
SERVER_API="http://${CENTERURL}/hmsvc/eqhw"
DATETIME=`date +'%Y-%m-%d %H:%M:%S'`
#UUID=`sudo dmidecode -t 1|grep UUID | awk -F ':' '{print $2}'`
UUID=`cat /etc/hamonize/uuid |head -1`
CPUID=`dmidecode -t 4|grep ID|awk -F ':' '{print $2}'`
CPUINFO=`cat /proc/cpuinfo | grep "model name" | head -1 | cut  -d" " -f3- | sed "s/^ *//g"`
#HDDID=`hdparm -I /dev/sda | grep 'Serial\ Number' |awk -F ':' '{print $2}'`
IPADDR=`ifconfig | awk '/inet .*broadcast/'|awk '{print $2}'`
MACADDR=`ifconfig | awk '/ether/'|awk '{print $2}'`
HOSTNAME=`hostname`
MEMORY=`awk '{ printf "%.2f", $2/1024/1024 ; exit}' /proc/meminfo`
HDDTMP=`fdisk -l | head -1 | awk '{print $2}'| awk -F':' '{print $1}'`
HDDID=`hdparm -I $HDDTMP  | grep 'Serial\ Number' |awk -F ':' '{print $2}'`
HDDINFO=`hdparm -I $HDDTMP  | grep 'Model\ Number' |awk -F ':' '{print $2}'`
ISGUESTCNT=`ls -t /tmp |grep ^guest-*|wc -l`
if [ "$ISGUESTCNT" -eq "1" ]; then
USER_HOME=`ls -t /tmp| grep ^guest-*|head -n 1`
USERID=`cat /tmp/$USER_HOME/.huserinfo | head -1 | awk -F ':' '{print $1}'`
else
USER_HOME=${HOME}
USERID=${USER}
fi

inxi -c0 -SGNM >> ${hw_path}/sgbpc_hw_chk
#diff_val=`diff -q ${hw_path}/sgbpc_hw_base ${hw_path}/sgbpc_hw_chk` >> /var/log/hamonize/sgbpc_hw_chk/sgbpc_hw_chk.log


#if [ -z "$diff_val" ]
#then
#	rm -fr ${hw_path}/sgbpc_hw_chk
#
#else
	#LOG="$UUID|$DATETIME|$CPUID|$CPUINFO|$HDDID|$HDDINFO|$MACADDR|$IPADDR|$HOSTNAME|$MEMORY|$SGBNAME"

    JSON="{\
            \"events\" : [ {\
            \"datetime\":\"$DATETIME\",\
            \"uuid\":\"$UUID\",\
            \"cpuid\": \"$CPUID\",\
            \"cpuinfo\": \"$CPUINFO\",\
            \"hddid\": \"$HDDID\",\
            \"hddinfo\": \"$HDDINFO\",\
            \"macaddr\": \"$MACADDR\",\
            \"ipaddr\": \"$IPADDR\",\
            \"hostname\": \"$HOSTNAME\",\
            \"memory\": \"$MEMORY\",\
            \"sgbname\": \"$SGBNAME\",\
            \"user\": \"$USERID\"\
            } ]\
    }"
echo $JSON
echo $SERVER_API
	#RETVAL=`curl  -X  POST -H 'User-Agent: HamoniKR OS' -H 'Content-Type: application/json' -f -s -d "$LOG_JSON" $SERVER_API`

	#RETVAL=`curl  -X  POST  -H 'Content-Type: application/json' -f -s -d "$LOG_JSON" $SERVER_API`

	dateval=`date +"%Y-%m-%d-%T"`
	#mv ${hw_path}/sgbpc_hw_chk ${hw_path}/sgb_pc_hw_chk_${dateval}

#fi

/usr/bin/curl -i -S \
-H "Accept: application/json" \
-H "Content-Type:application/json" \
-X POST -d "${JSON}" $SERVER_API
